--------------------------------------------------------
-- Archivo creado  - miércoles-abril-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "JONATHAN2693"."EMPLOYEES" 
   (	"EMPLOYEE_NUMBER" NUMBER(10,0), 
	"EMPLOYEE_NAME" VARCHAR2(50 BYTE), 
	"EMPLOYEE_DEPARTMENT" VARCHAR2(50 BYTE), 
	"EMPLOYEE_RFC" VARCHAR2(20 BYTE), 
	"EMPLOYEE_EMAIL" VARCHAR2(20 BYTE), 
	"EMPLOYEE_PHONE" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ADDRESS" VARCHAR2(20 BYTE), 
	"EMPLOYEE_REGISTRATION_DATE" DATE, 
	"EMPLOYEE_STATUS" NUMBER(10,0), 
	"SALARY" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JONATHAN2693.EMPLOYEES
SET DEFINE OFF;
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (11,'Jonathan','TTAA','QURJ930726EV3','joa3@gmail.com','5585848489','California',to_date('24/03/22','DD/MM/RR'),1,15000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (12,'Jonathan Quino','TTAA','QURJ930726ED4','jquino@minsait.com','5584403413','Ecatepec',to_date('13/03/17','DD/MM/RR'),0,9000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (5,'Jonathan Quino','GAS&OIL','QURJ930726ER3','jonaQ@gmail.com','5585848432','Mexico',to_date('19/04/22','DD/MM/RR'),1,156500);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (1,'Jonathan','TTAA','QURJ930726EE3','jona3@gmail.com','5585848489','California',to_date('24/03/22','DD/MM/RR'),1,15000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (6,'Jonathan OMar','Sun','QURJ931726ER3','j.quino@gmail.com','5585848443','Mexico',to_date('13/03/17','DD/MM/RR'),1,9000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (3,'Jonathan','TTAA','QURJ930726EV3','joa3@gmail.com','5585848489','California',to_date('24/03/22','DD/MM/RR'),1,15000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (9,'Jonathan OMar','Sun','QURJ931726ER3','j.quino@gmail.com','5585848443','Mexico',to_date('13/03/17','DD/MM/RR'),1,9000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (10,'Jonathan','TTAA','QURJ930726EV3','joa3@gmail.com','5585848489','California',to_date('24/03/22','DD/MM/RR'),0,15000);
Insert into JONATHAN2693.EMPLOYEES (EMPLOYEE_NUMBER,EMPLOYEE_NAME,EMPLOYEE_DEPARTMENT,EMPLOYEE_RFC,EMPLOYEE_EMAIL,EMPLOYEE_PHONE,EMPLOYEE_ADDRESS,EMPLOYEE_REGISTRATION_DATE,EMPLOYEE_STATUS,SALARY) values (4,'Jonathan','TTAA','QURJ930726ED9','jona2@gmail.com','5585848489','California',to_date('24/03/22','DD/MM/RR'),1,15000);
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JONATHAN2693"."EMPLOYEES_PK" ON "JONATHAN2693"."EMPLOYEES" ("EMPLOYEE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "JONATHAN2693"."EMPLOYEES" MODIFY ("EMPLOYEE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "JONATHAN2693"."EMPLOYEES" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
  ALTER TABLE "JONATHAN2693"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
